language: node_js
node_js:
  - "6.9"
  - "7.5"
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - "test ! -d node_modules || yarn clean"
script:
  - "yarn run test-ci"
after_script:
  - "yarn add coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"

