language: node_js
node_js:
  - "6.9"
  - "7.5"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm test"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
